### ISSUE TITLE
pdos calculations

### ISSUE THREAD

**Issue by Wenbintum** [lmmentel/ase-espresso#13]
Hi Łukasz,

Thanks for making this powerful tool in python 3 compatibilities.  Did you ever test the function of calculating pdos？
As seen, I can not find such an example in the test folder, and also there are still some 'old' functions that remain such as site.perHostMpiExec, site.runonly_perProcMpiExec which are not in siteconfig.py any more. Any suggestion to easily make pdos calculation feasible?

Thanks a lot !

**Comment by lmmentel** [comment]
I don't remember ever using the pdos functionality, and probably that's the reason why it's not refactored completely. If you want to make it work you would need to replace the calls in `run_espressox` with the appropriate calls from `siteconfig.py`. Look at some the other places in `espresso.py` module where `site` functions are called since that might give you a hint how to refactor. Good luck!
